# fly.toml app configuration file generated for telegram-stt-bot on 2025-07-20T20:13:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-stt-bot'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  RUST_BACKTRACE = '1'
  RUST_LOG = 'info'

[processes]
  app = ''

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  ports = []
  processes = ['app']

  [services.concurrency]
    type = 'requests'
    hard_limit = 1000
    soft_limit = 100

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  processes = ['app']
